(function ensightenInit(){var ensightenOptions = {client: "choozle", clientId: 923, publishPath: "17160", bootstrapVersion: "v8_20220915", isPublic:0, serverComponentLocation: "nexus.ensighten.com/choozle/17160/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/choozle/17160/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Thu Sep 28 22:31:49 GMT 2023", beaconSamplingSeedValue: 11, dataLayerName: "ensDataLayer"};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(l){function n(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function p(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function q(){for(var a=c.dataDefinitionIds.length,b=!0,e=0;e<a;e++){var f=c.dataDefinitions[c.dataDefinitionIds[e]];if(!f||
null==f.endRegistration){b=!1;break}}b&&c.callOnDataDefintionComplete()}var d={},c={};c.ensightenOptions=ensightenOptions;c.scDataObj={};d.version="1.26.0";d.getDynamicDomain=function(){var a=document.currentScript&&document.currentScript.src?(new URL(document.currentScript.src)).hostname:"";if(a)return a;a=null;for(var b=document.getElementsByTagName("script"),e=l.client+"/"+l.publishPath+"/Bootstrap.js",f=l.client+"/Bootstrap.js",g=0;g<b.length;g++)if(-1<b[g].src.indexOf(e)||"prod"==l.publishPath&&
-1<b[g].src.indexOf(f)){a=b[g];break}return a?(b=document.createElement("a"),b.href=a.getAttribute("src"),b.hostname):""};ensightenOptions.nexus=d.nexus=ensightenOptions.nexus||d.getDynamicDomain()||"nexus.ensighten.com";d.rand=-1;d.currSec=(new Date).getSeconds();d.options={interval:l.interval||100,erLoc:l.errorLocation||d.nexus+"/error/e.gif",scLoc:l.serverComponentLocation||d.nexus+"/"+l.client+"/serverComponent.php",sjPath:l.staticJavascriptPath||d.nexus+"/"+l.client+"/code/",alLoc:l.alertLocation||
d.nexus+"/alerts/a.gif",publishPath:l.publishPath,isPublic:l.isPublic,client:l.client,clientId:l.clientId,enableTagAuditBeacon:l.enableTagAuditBeacon,beaconSamplingSeedValue:l.beaconSamplingSeedValue||-1,dataLayerName:l.dataLayerName||"ensDataLayer"};d.ruleList=[];d.allDeploymentIds=[];d.runDeploymentIds=[];d.runRuleIds=[];d.exceptionList=[];d.ensightenVariables={};d.appIdWhitelist=[];d.appIdBlacklist=[];window[d.options.dataLayerName]&&window[d.options.dataLayerName][0]&&(window[d.options.dataLayerName][0]["ens.whitelist"]&&
(d.appIdWhitelist=window[d.options.dataLayerName][0]["ens.whitelist"]),window[d.options.dataLayerName][0]["ens.blacklist"]&&(d.appIdBlacklist=window[d.options.dataLayerName][0]["ens.blacklist"]));d.canRuleRunByAppId=function(a){return a?a&&!a.appId||a&&-1==a.appId||0==d.appIdWhitelist.length&&0==d.appIdBlacklist.length?!0:0<d.appIdWhitelist.length&&0==d.appIdBlacklist.length?-1==d.appIdWhitelist.indexOf(a.appId)?!1:!0:0==d.appIdWhitelist.length&&0<d.appIdBlacklist.length?-1==d.appIdBlacklist.indexOf(a.appId)?
!0:!1:0<d.appIdWhitelist.length&&0<d.appIdBlacklist.length&&-1==d.appIdBlacklist.indexOf(a.appId)&&-1!=d.appIdWhitelist.indexOf(a.appId)?!0:!1:!1};d.test=function(a){if(d.canRuleRunByAppId(a)&&!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;a.execute()}};n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;d.DependencyNotAvailableException=n;p.prototype=Error();p.prototype||
(p.prototype={});p.prototype.constructor=p;d.BeaconException=p;d.checkForInvalidDependencies=function(a,b,e,f){for(a=0;a<e.length;a++)if("DEPENDENCYNEVERAVAILABLE"===e[a])return c.currentRuleId=this.id,c.currentDeploymentId=this.deploymentId,c.reportException(new d.DependencyNotAvailableException(f[a])),b&&-1!==b&&d.allDeploymentIds.push(b),!0;return!1};c.currentRuleId=-1;c.currentDeploymentId=-1;c.reportedErrors=[];c.reportedAlerts=[];c.AF=[];c._serverTime="";c._clientIP="";c.sampleBeacon=function(){var a=
!1;try{var b=(d.currSec||0)%20,e=d.options.beaconSamplingSeedValue;-1===e?a=!0:0!==b&&0===e%b&&(a=!0)}catch(f){}return a};c.getServerComponent=function(a){c.callOnGetServerComponent();var b=window.location.protocol+"//"+("/"==d.options.scLoc.charAt(0)?d.getDynamicDomain():"")+d.options.scLoc;c.insertScript(b,!1,a||!0,!0)};c.setVariable=function(a,b){d.ensightenVariables[a]=b};c.getVariable=function(a){return a in d.ensightenVariables?d.ensightenVariables[a]:null};c.testAll=function(){for(var a=0;a<
d.ruleList.length;a++)d.test(d.ruleList[a])};c.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};c.reportException=function(a){a.timestamp=(new Date).getTime();d.exceptionList.push(a);a=window.location.protocol+"//"+d.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(d.options.clientId||-1)+"&client="+encodeURIComponent(d.options.client||
"")+"&publishPath="+encodeURIComponent(d.options.publishPath||"")+"&rid="+encodeURIComponent(c.currentRuleId||-1)+"&did="+encodeURIComponent(c.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=c.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a);c.currentRuleId=-1;c.currentDeploymentId=-1};c.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);c.currentRuleId=this.id;c.currentDeploymentId=this.deploymentId;try{this.code()}catch(b){window[ensightenOptions.ns].reportException(b)}finally{this.executionData.hasRun=
!0,-1!==this.deploymentId&&(d.runDeploymentIds.push(this.deploymentId),d.runRuleIds.push(this.id)),c.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.appId=a.appId;this.executionData={hasRun:!1,runTime:[]}};c.registerRule=function(a){if(c.getRule(a.id)&&-1!==a.id)return!1;d.ruleList.push(a);-1!==a.deploymentId&&d.allDeploymentIds.push(a.deploymentId);c.testAll();return!0};c.getRule=function(a){for(var b=0;b<d.ruleList.length;b++)if(d.ruleList[b].id===
a)return d.ruleList[b];return!1};c.getRuleList=function(){return d.ruleList};c.clearRuleList=function(){d.ruleList=[]};c.getAllDeploymentIds=function(){return d.allDeploymentIds};c.getRunRuleIds=function(){return d.runRuleIds};c.getRunDeploymentIds=function(){return d.runDeploymentIds};c.hasRuleRun=function(a){return(a=c.getRule(a))?a.executionData.hasRun:!1};d.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};c.Alert=function(a){var b=new Date;b=b.getFullYear()+"-"+d.toTwoChar(b.getMonth())+
"-"+d.toTwoChar(b.getDate())+" "+d.toTwoChar(b.getHours())+":"+d.toTwoChar(b.getMinutes())+":"+d.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};c.generateAlert=function(a){a=c.imageRequest(window.location.protocol+"//"+d.options.alLoc+"?d="+a.date+"&su="+
a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+d.options.clientId+"&client="+d.options.client+"&publishPath="+d.options.publishPath+"&rid="+c.currentRuleId+"&did="+c.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};c.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};c.insertScript=function(a,b,e,f){var g=document.getElementsByTagName("script"),h;if(void 0!==b?b:1)for(h=0;h<g.length;h++)if(g[h].src===a&&g[h].readyState&&/loaded|complete/.test(g[h].readyState))return;
if(!f)var m=e;else if(e){e=1==e&&"object"==typeof c.scDataObj?c.scDataObj:e;d.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));b=window.location.href;"object"===typeof e&&e.PageID&&(b=e.PageID,delete e.PageID);if("object"===typeof e)for(h in e){h=~b.indexOf("#")?b.slice(b.indexOf("#"),b.length):"";b=b.slice(0,h.length?b.length-h.length:b.length);b+=~b.indexOf("?")?"&":"?";for(k in e)b+=k+"="+e[k]+"&";b=b.slice(0,-1)+h;break}a=a+"?namespace="+(ensightenOptions.ns+"&");a+="staticJsPath="+ensightenOptions.staticJavascriptPath+
"&";a+="publishedOn="+ensightenOptions.generatedOn+"&";a+="ClientID="+encodeURIComponent(d.options.clientId)+"&PageID="+encodeURIComponent(b)+("/"==d.options.scLoc.charAt(0)?"&custDomain="+d.getDynamicDomain():"")}(function(r,w,x){var t=w.head||w.getElementsByTagName("head"),y=function(){if("item"in t){if(!t[0]){setTimeout(y,25);return}t=t[0]}var u=w.createElement("script"),v;for(v in m)u.setAttribute(v,m[v]?m[v]:null);x&&(u.src=x);u.onload=u.onerror=function(){this.addEventListener&&(this.readyState=
"loaded")};t.insertBefore(u,t.firstChild)};setTimeout(y,0)})(window,document,a,m)};c.loadScriptCallback=function(a,b,e){var f=document.getElementsByTagName("script"),g=f[0];if(e)for(e=0;e<f.length;e++)if(f[e].src===a&&f[e].readyState&&/loaded|complete/.test(f[e].readyState))try{b()}catch(h){window[ensightenOptions.ns].reportException(h)}finally{return}f=document.createElement("script");f.type="text/javascript";f.async=!0;f.src=a;f.onerror=function(){this.addEventListener&&(this.readyState="loaded")};
f.onload=f.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(h){window[ensightenOptions.ns].reportException(h)}}};g.parentNode.insertBefore(f,g)};c.insertPageFiles=function(a){var b=0,e=0,f=function(){e==a.length-1&&window[ensightenOptions.ns].callOnPageSpecificCompletion();e++};for(b=0;b<a.length;++b)window[ensightenOptions.ns].loadScriptCallback(a[b],
f)};c.unobtrusiveAddEvent=function(a,b,e){try{var f=a[b]?a[b]:function(){};a[b]=function(){e.apply(this,arguments);return f.apply(this,arguments)}}catch(g){window[ensightenOptions.ns].reportException(g)}};c.anonymous=function(a,b){return function(){try{c.currentRuleId=b?b:"anonymous",a()}catch(e){window[ensightenOptions.ns].reportException(e)}}};c.setCurrentRuleId=function(a){c.currentRuleId=a};c.setCurrentDeploymentId=function(a){c.currentDeploymentId=a};d.bind=function(a,b,e,f,g){if("function"===
typeof a)a=new c.Rule({id:b||-1,deploymentId:e||-1,appId:f||-1,dependencies:"immediate"==g?[]:[function(){return window[ensightenOptions.ns].executionState[g]}],code:a});else if("object"!==typeof a)return!1;c.registerRule(a)};c.bindImmediate=function(a,b,e,f){d.bind(a,b,e,f,"immediate")};c.bindDOMParsed=function(a,b,e,f){d.bind(a,b,e,f,"DOMParsed")};c.bindDOMLoaded=function(a,b,e,f){d.bind(a,b,e,f,"DOMLoaded")};c.bindPageSpecificCompletion=function(a,b,e,f){d.bind(a,b,e,f,"conditionalRules")};c.bindOnGetServerComponent=
function(a,b,e,f){d.bind(a,b,e,f,"readyForServerComponent")};c.bindDataDefinitionComplete=function(a,b,e,f){d.bind(a,b,e,f,"dataDefinitionComplete")};c.checkHasRun=function(a){if(0===a.length)return!0;for(var b,e=0;e<a.length;++e)if(b=c.getRule(parseInt(a[e],10)),!b||!b.executionData.hasRun)return!1;return!0};d.bindDependency=function(a,b,e,f,g,h,m){var r=[];if(!d.checkForInvalidDependencies(b,f,e,g)){"immediate"==!m&&r.push(function(){return window[ensightenOptions.ns].executionState[m]});r.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});
if("function"===typeof a)a=new c.Rule({id:b||-1,deploymentId:f||-1,appId:h||-1,dependencies:r,code:a});else if("object"!==typeof a)return!1;c.registerRule(a)}};c.bindDependencyImmediate=function(a,b,e,f,g,h){d.bindDependency(a,b,e,f,g,h,"immediate")};c.bindDependencyDOMLoaded=function(a,b,e,f,g,h){d.bindDependency(a,b,e,f,g,h,"DOMLoaded")};c.bindDependencyDOMParsed=function(a,b,e,f,g,h){d.bindDependency(a,b,e,f,g,h,"DOMParsed")};c.bindDependencyPageSpecificCompletion=function(a,b,e,f,g,h){d.bindDependency(a,
b,e,f,g,h,"conditionalRules")};c.bindDependencyOnGetServerComponent=function(a,b,e,f,g,h){d.bindDependency(a,b,e,f,g,h,"readyForServerComponent")};c.bindDependencyDataDefinitionComplete=function(a,b,e,f,g,h){d.bindDependency(a,b,e,f,g,h,"dataDefinitionComplete")};c.dataDefintionIds=[];c.dataDefinitions=[];c.pageSpecificDataDefinitionsSet=!1;c.setPageSpecificDataDefinitionIds=function(a){for(var b=a?a.length:0,e=0;e<b;e++){var f=a[e];if(Array.prototype.indexOf)-1==c.dataDefinitionIds.indexOf(f)&&c.dataDefinitionIds.push(f);
else{for(var g=!1,h=c.dataDefinitionIds.length,m=0;m<h;m++)if(c.dataDefinitionIds[m]===f){g=!0;break}g||c.dataDefinitionIds.push(f)}}c.pageSpecificDataDefinitionsSet=!0;q()};c.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};c.registerDataDefinition=function(a,b){var e=c.dataDefinitions[b];e||
(e=new c.DataDefinition(b,a),c.dataDefinitions[b]=e);e.startRegistrationTime||(e.startRegistration(),e.registrationFn(),e.endRegistration());c.pageSpecificDataDefinitionsSet&&q()};c.callOnDataDefintionComplete=function(){c.executionState.dataDefinitionComplete=!0;c.testAll()};c.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};c.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=
!0;window[ensightenOptions.ns].testAll()};c.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,e=a.length;b<e;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};c.callOnGetServerComponent=
function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};c.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};c.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};c.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var z=function(){var a=[],b=!1,e=!1;return{add:function(f){b&&!e?f():"function"==typeof f&&(a[a.length]=
f)},exec:function(){e=!0;do{var f=a;a=[];b=!0;for(var g=0;g<f.length;g++)try{f[g].call(window)}catch(h){window[ensightenOptions.ns].reportException(h)}}while(0<a.length);e=!1},haveRun:function(){return b}}};c.new_fArray=function(){return z()};d.timer=null;(function(){function a(f,g){return function(){f.apply(g,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var e=log4javascript.getDefaultLogger();b.log=a(e.info,e);b.debug=a(e.debug,e);b.info=
a(e.info,e);b.warn=a(e.warn,e);b.error=a(e.error,e)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?d.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(d.timer),c.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",c.callOnDOMParsed,!1),window.addEventListener("load",c.callOnDOMLoaded,
!1)):(setTimeout(function(){var a=window.document,b=function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(e){setTimeout(b,15);return}window[ensightenOptions.ns].callOnDOMParsed()};b()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&"complete"===document.readyState&&(c.executionState.DOMParsed=!0,c.executionState.DOMLoaded=!0);"true"===d.options.enableTagAuditBeacon&&c.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&
!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],b,e,f,g,h=0;h<d.ruleList.length;++h)e=d.ruleList[h],f=e.executionData.hasRun?"1":"0",g=e.deploymentId.toString()+"|"+e.id.toString()+"|"+f,a.push(g);b="["+a.join(";")+"]";var m=window.location.protocol+"//"+d.nexus+"/"+encodeURIComponent(l.client)+"/"+encodeURIComponent(l.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(l.clientId)+"&data="+b+"&idx=0&r="+d.rand;c.imageRequest(m)}catch(r){c.currentRuleId=-1,c.currentDeploymentId=
-1,a=new d.BeaconException(r),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(c.testAll,d.options.interval);return c}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var l=window.performance;if(l){l=l.timing||{};var n=l.navigationStart||0,p={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var q="&ns="+encodeURIComponent(l.navigationStart);for(var d in p)if(void 0!==l[d]){var c=l[d]-n;q+="&"+p[d]+"="+(0<c?encodeURIComponent(c):0)}else q+="&"+p[d]+"=-1";window[ensightenOptions.ns].timing=q;d=ensightenOptions.nexus||"nexus.ensighten.com";l=ensightenOptions.staticJavascriptPath||
"";q=l.indexOf("/",0);n=l.indexOf("/code/");l=l.substring(q,n)+"/perf.rnc";l+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+d+l)}}});

  window[ensightenOptions.ns].ensEvent||(window[ensightenOptions.ns].ensEvent=function(v,F){var n={queue:{},pollQueue:{},pushTrigger:function(e,h){if("[object Array]"===Object.prototype.toString.call(e)){for(var f=0;f<e.length;f++)n.pushTrigger(e[f],h);return!0}if("string"!=typeof e)return!1;this.queue[e]=this.queue[e]||{fn:[]};"function"==typeof h&&this.queue[e].fn.push(h);n.addEventRunTime("eventsAdded",e);return!0},callTrigger:function(e,h,f){if("string"!=typeof e)return!1;f=n.queue[e];if("object"==
  typeof f&&f.fn&&f.fn.length&&(0!=f.fireOnFirstSet&&h==F||h!=F&&0!=f.fireOnUpdate))for(h=0;h<f.fn.length;h++)try{f.fn[h].call(this),n.addEventRunTime("eventsTriggered",e)}catch(z){v[ensightenOptions.ns].reportException(z)}},setPollOptions:function(e,h,f){this.queue[e]=this.queue[e]||{fn:[]};this.queue[e].fireOnFirstSet=h;this.queue[e].fireOnUpdate=f},callPoll:function(e,h,f,z,A){if("string"==typeof e&&h&&h.length&&!(1>h.length)){for(var D=0;D<h.length;D++)n.setPollOptions(h[D],z,A);n.pushWatch(e,h,
  f)}},pushWatch:function(e,h,f){this.pollQueue[e]||(this.pollQueue[e]={previousVal:F,eventArr:[],valueFn:f});this.pollQueue[e].eventArr=this.pollQueue[e].eventArr.concat(h);this.pollQueue[e].valueFn=f},globalWatch:function(){setInterval(function(){for(var e in n.pollQueue){var h=n.pollQueue[e],f=h.valueFn(e);if(h.previousVal!==f&&null!==f){for(var z=0;z<h.eventArr.length;z++)n.callTrigger.call(v,h.eventArr[z],h.previousVal,f);n.pollQueue[e].previousVal=f}}},500)},addEventRunTime:function(e,h){var f=
  v[ensightenOptions.ns].ensEvent;f[e]=f[e]||{};f[e][h]=f[e][h]||{runTimes:[]};f[e][h].runTimes.push((new Date).getTime())}};n.globalWatch();return{add:function(e,h){return n.pushTrigger(e,h)},get:function(e){return n.queue[e]},trigger:function(e,h){var f=h||v;v[ensightenOptions.ns].data=v[ensightenOptions.ns].data||{};v[ensightenOptions.ns].data.event_param=f||{};return n.callTrigger.call(f||Bootstrapper,e)},poll:function(e,h,f,z,A){A=A||v[ensightenOptions.ns].data.resolve;return n.callPoll(e,h,A,
  f,z)}}}(window),function(v,F,n){F[v]=n()}("qwery",window[ensightenOptions.ns],function(){function v(){this.c={}}function F(a){return V.g(a)||V.s(a,"(^|\\s+)"+a+"(\\s+|$)",1)}function n(a,b){for(var c=0,l=a.length;c<l;c++)b(a[c])}function e(a){for(var b=[],c=0,l=a.length;c<l;++c)k(a[c])?b=b.concat(a[c]):b[b.length]=a[c];return b}function h(a){for(var b=0,c=a.length,l=[];b<c;b++)l[b]=a[b];return l}function f(a){for(;(a=a.previousSibling)&&1!=a.nodeType;);return a}function z(a,b,c,l,m,y,r,B,w,K,L){var M,
  G,R;if(1!==this.nodeType||b&&"*"!==b&&this.tagName&&this.tagName.toLowerCase()!==b||c&&(M=c.match(S))&&M[1]!==this.id)return!1;if(c&&(R=c.match(P)))for(a=R.length;a--;)if(!F(R[a].slice(1)).test(this.className))return!1;if(w&&t.pseudos[w]&&!t.pseudos[w](this,L))return!1;if(l&&!r)for(G in w=this.attributes,w)if(Object.prototype.hasOwnProperty.call(w,G)&&(w[G].name||G)==m)return this;return l&&!D(y,ba(this,m)||"",r)?!1:this}function A(a){return W.g(a)||W.s(a,a.replace(ca,"\\$1"))}function D(a,b,c){switch(a){case "=":return b==
  c;case "^=":return b.match(H.g("^="+c)||H.s("^="+c,"^"+A(c),1));case "$=":return b.match(H.g("$="+c)||H.s("$="+c,A(c)+"$",1));case "*=":return b.match(H.g(c)||H.s(c,A(c),1));case "~=":return b.match(H.g("~="+c)||H.s("~="+c,"(?:^|\\s+)"+A(c)+"(?:\\s+|$)",1));case "|=":return b.match(H.g("|="+c)||H.s("|="+c,"^"+A(c)+"(-|$)",1))}return 0}function x(a,b){var c=[],l=[],m,y,r=b,B=Q.g(a)||Q.s(a,a.split(X)),w=a.match(Y);if(!B.length)return c;var K=(B=B.slice(0)).pop();B.length&&(m=B[B.length-1].match(I))&&
  (r=u(b,m[1]));if(!r)return c;var L=K.match(T);var M=r!==b&&9!==r.nodeType&&w&&/^[+~]$/.test(w[w.length-1])?function(G){for(;r=r.nextSibling;)1==r.nodeType&&(L[1]?L[1]==r.tagName.toLowerCase():1)&&(G[G.length]=r);return G}([]):r.getElementsByTagName(L[1]||"*");m=0;for(K=M.length;m<K;m++)if(y=z.apply(M[m],L))c[c.length]=y;if(!B.length)return c;n(c,function(G){E(G,B,w)&&(l[l.length]=G)});return l}function E(a,b,c,l){function m(r,B,w){for(;w=da[c[B]](w,r);)if(d(w)&&z.apply(w,b[B].match(T)))if(B){if(y=
  m(w,B-1,w))return y}else return w}var y;return(y=m(a,b.length-1,a))&&(!l||N(y,l))}function d(a,b){return a&&"object"===typeof a&&(b=a.nodeType)&&(1==b||9==b)}function g(a){var b=[],c;var l=0;a:for(;l<a.length;++l){for(c=0;c<b.length;++c)if(b[c]==a[l])continue a;b[b.length]=a[l]}return b}function k(a){return"object"===typeof a&&isFinite(a.length)}function u(a,b,c){return 9===a.nodeType?a.getElementById(b):a.ownerDocument&&((c=a.ownerDocument.getElementById(b))&&N(c,a)&&c||!N(a,a.ownerDocument)&&J('[id="'+
  b+'"]',a)[0])}function t(a,b){var c,l;var m=b?"string"==typeof b?t(b)[0]:!b.nodeType&&k(b)?b[0]:b:q;if(!m||!a)return[];if(a===window||d(a))return!b||a!==window&&d(m)&&N(a,m)?[a]:[];if(a&&k(a))return e(a);if(c=a.match(ea)){if(c[1])return(l=u(m,c[1]))?[l]:[];if(c[2])return h(m.getElementsByTagName(c[2]));if(fa&&c[3])return h(m.getElementsByClassName(c[3]))}return J(a,m)}function p(a,b){return function(c){var l,m;Z.test(c)?9!==a.nodeType&&((m=l=a.getAttribute("id"))||a.setAttribute("id",m="__qwerymeupscotty"),
  c='[id="'+m+'"]'+c,b(a.parentNode||a,c,!0),l||a.removeAttribute("id")):c.length&&b(a,c,!1)}}var q=document,C=q.documentElement,J,S=/#([\w\-]+)/,P=/\.[\w\-]+/g,I=/^#([\w\-]+)$/,ha=/^([\w]+)?\.([\w\-]+)$/,Z=/(^|,)\s*[>~+]/,ia=/^\s+|\s*([,\s\+~>]|$)\s*/g,O=/[\s>\+~]/,aa=/(?![\s\w\-\/\?&=:\.\(\)!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,ca=/([.*+?\^=!:${}()|\[\]\/\\])/g,ea=new RegExp(I.source+"|"+/^([\w\-]+)$/.source+"|"+/^\.([\w\-]+)$/.source),Y=new RegExp("("+O.source+")"+aa.source,"g"),X=new RegExp(O.source+
  aa.source),T=new RegExp(/^(\*|[a-z0-9]+)?(?:([\.#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*~]?=)['"]?([ \w\-\/\?&=:\.\(\)!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),da={" ":function(a){return a&&a!==C&&a.parentNode},">":function(a,b){return a&&a.parentNode==b.parentNode&&a.parentNode},"~":function(a){return a&&a.previousSibling},"+":function(a,b,c,l){return a?(c=f(a))&&(l=f(b))&&c==l&&c:!1}};v.prototype={g:function(a){return this.c[a]||
  void 0},s:function(a,b,c){b=c?new RegExp(b):b;return this.c[a]=b}};var V=new v,W=new v,H=new v,Q=new v,N="compareDocumentPosition"in C?function(a,b){return 16==(b.compareDocumentPosition(a)&16)}:"contains"in C?function(a,b){b=9===b.nodeType||b==window?C:b;return b!==a&&b.contains(a)}:function(a,b){for(;a=a.parentNode;)if(a===b)return 1;return 0},ba=function(){var a=q.createElement("p");return(a.innerHTML='<a href="#x">x</a>',"#x"!=a.firstChild.getAttribute("href"))?function(b,c){return"class"===c?
  b.className:"href"===c||"src"===c?b.getAttribute(c,2):b.getAttribute(c)}:function(b,c){return b.getAttribute(c)}}(),fa=!!q.getElementsByClassName,ja=q.querySelector&&q.querySelectorAll,ka=function(a,b){var c=[],l,m;try{if(9===b.nodeType||!Z.test(a))return h(b.querySelectorAll(a));n(l=a.split(","),p(b,function(y,r){m=y.querySelectorAll(r);1==m.length?c[c.length]=m.item(0):m.length&&(c=c.concat(h(m)))}));return 1<l.length&&1<c.length?g(c):c}catch(y){}return U(a,b)},U=function(a,b){var c=[],l,m;a=a.replace(ia,
  "$1");if(l=a.match(ha)){var y=F(l[2]);l=b.getElementsByTagName(l[1]||"*");var r=0;for(m=l.length;r<m;r++)y.test(l[r].className)&&(c[c.length]=l[r]);return c}n(l=a.split(","),p(b,function(B,w,K){y=x(w,B);r=0;for(m=y.length;r<m;r++)if(9===B.nodeType||K||N(y[r],b))c[c.length]=y[r]}));return 1<l.length&&1<c.length?g(c):c};O=function(a){"undefined"!==typeof a.useNativeQSA&&(J=a.useNativeQSA?ja?ka:U:U)};O({useNativeQSA:!0});t.configure=O;t.uniq=g;t.is=function(a,b,c){if(d(b))return a==b;if(k(b))return!!~e(b).indexOf(a);
  for(var l=b.split(","),m;b=l.pop();)if(m=Q.g(b)||Q.s(b,b.split(X)),b=b.match(Y),m=m.slice(0),z.apply(a,m.pop().match(T))&&(!m.length||E(a,m,b,c)))return!0;return!1};t.pseudos={};return t}),function(){function v(d,g,k){z||(z=window[ensightenOptions.ns].qwery);var u=z;if((u=u.call(k,g,k))&&0<u.length){if("_root"==g)d=k;else if(d===k)d=void 0;else{b:{for(var t=u.length,p=0;p<t;p++)if(d===u[p]){u=!0;break b}u=!1}u||(d.parentNode?(A++,d=v(d.parentNode,g,k)):d=void 0)}return d}return!1}function F(d,g,k,
  u){x[d.id]||(x[d.id]={});x[d.id][g]||(x[d.id][g]={});x[d.id][g][k]||(x[d.id][g][k]=[]);x[d.id][g][k].push(u)}function n(d,g,k,u){if(u||k)if(u)for(var t=0;t<x[d.id][g][k].length;t++){if(x[d.id][g][k][t]===u){x[d.id][g][k].pop(t,1);break}}else delete x[d.id][g][k];else x[d.id][g]={}}function e(d,g,k){if(x[d][k]){var u=g.target||g.srcElement,t,p,q={},C=p=0;A=0;for(t in x[d][k])x[d][k].hasOwnProperty(t)&&(p=v(u,t,E[d].element))&&f.matchesEvent(k,E[d].element,p,"_root"==t,g)&&(A++,x[d][k][t].match=p,q[A]=
  x[d][k][t]);g.stopPropagation=function(){g.cancelBubble=!0};for(p=0;p<=A;p++)if(q[p])for(C=0;C<q[p].length;C++){if(!1===q[p][C].call(q[p].match,g)){f.cancel(g);return}if(g.cancelBubble)return}}}function h(d,g,k,u){function t(C){return function(J){e(p,J,C)}}d instanceof Array||(d=[d]);k||"function"!=typeof g||(k=g,g="_root");var p=this.id,q;for(q=0;q<d.length;q++)x[p]&&x[p][d[q]]||f.addEvent(this,d[q],t(d[q])),u?n(this,d[q],g,k):F(this,d[q],g,k);return this}function f(d,g,k,u){if("string"==typeof d&&
  "function"==typeof g||"string"==typeof g)f(document).on(d,g,k,u||!1);if(!(this instanceof f)){for(var t in E)if(E[t].element===d)return E[t];D++;E[D]=new f(d,D);E[D]._on=E[D].on;E[D].on=function(p,q,C,J){var S="function"==typeof q?q:C;if("function"==typeof q?C:J)p=[p],"string"==typeof q&&p.push(q),p.push(function(P){return function(I){I.defaultPrevented||window[ensightenOptions.ns].Delegate.load(this);if(this.nodeName&&"a"!=this.nodeName.toLowerCase())return P.call(this);"undefined"!=typeof I.preventDefault?
  I.preventDefault():I.returnValue=!1;P.call(this)}}(S)),this._on.apply(this,p);else return this._on.call(this,p,q,C)};return E[D]}this.element=d;this.id=g}var z,A=0,D=0,x={},E={};f.prototype.on=function(d,g,k){return h.call(this,d,g,k)};f.prototype.off=function(d,g,k){return h.call(this,d,g,k,!0)};f.cancel=function(d){d.preventDefault();d.stopPropagation()};f.addEvent=function(d,g,k){d.element.addEventListener(g,k,"blur"==g||"focus"==g)};f.matchesEvent=function(){return!0};f.load=function(d){setTimeout(function(g,
  k){var u=g.getAttribute("target")||"_self";return function(){if(g.nodeName&&"a"==g.nodeName.toLowerCase()){if(k&&/^javascript\s*:/.test(k))return(new Function(unescape(k))).call(window);k&&window.open(k,u)}}}(d,d.href||""),750)};window[ensightenOptions.ns].Delegate=f}(),function(v){var F=v.addEvent;v.addEvent=function(n,e,h){if(n.element.addEventListener)return F(n,e,h);"focus"==e&&(e="focusin");"blur"==e&&(e="focusout");n.element.attachEvent("on"+e,h)};v.cancel=function(n){n.preventDefault&&n.preventDefault();
  n.stopPropagation&&n.stopPropagation();n.returnValue=!1;n.cancelBubble=!0}}(window[ensightenOptions.ns].Delegate),window[ensightenOptions.ns].on=window[ensightenOptions.ns].Delegate);
Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.loadScriptCallback("https://js.adsrvr.org/up_loader.1.1.0.js",function(){(function(){(function(){ttd_dom_ready(function(){if(typeof TTDUniversalPixelApi==="function"){var universalPixelApi=new TTDUniversalPixelApi;universalPixelApi.init("7rnutj6",["m7kd3xm"],"https://insight.adsrvr.org/track/up")}})}).call(window)}).call(window)})},3866495,741534,3);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();